spring.application.name=bonus
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.enabled=true
spring.jpa.hibernate.ddl-auto=update